#%RAML 1.0
title: unitedapi
baseUri: http://localhost:8081/api
/unitedflights:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/listAllUnitedFlights-get-response.json

  /{destination}:
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/unitedFlightsByDestination-get-response.json
                
              


              
  